package org.iscas.tj2.pyt.springboot_mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.iscas.tj2.pyt.springboot_mybatis.domain.Function;
import org.iscas.tj2.pyt.springboot_mybatis.domain.Macro;

public interface MacroMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer idMacro);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	int insert(Macro record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	int insertSelective(Macro record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	Macro selectByPrimaryKey(Integer idMacro);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	int updateByPrimaryKeySelective(Macro record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	int updateByPrimaryKey(Macro record);

	//2018-12-27
	List<Macro> selectMacroesByProjectId(@Param("IdProject") int intProjectId);
}