package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.MacroProjectRelation;

public interface MacroProjectRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer idMacroprojectrelation);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	int insert(MacroProjectRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	int insertSelective(MacroProjectRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	MacroProjectRelation selectByPrimaryKey(Integer idMacroprojectrelation);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	int updateByPrimaryKeySelective(MacroProjectRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	int updateByPrimaryKey(MacroProjectRelation record);
}