package org.iscas.tj2.pyt.springboot_mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.iscas.tj2.pyt.springboot_mybatis.domain.TypeItem;

public interface TypeItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    int deleteByPrimaryKey(Integer idTypeitem);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    int insert(TypeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    int insertSelective(TypeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    TypeItem selectByPrimaryKey(Integer idTypeitem);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    int updateByPrimaryKeySelective(TypeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    int updateByPrimaryKey(TypeItem record);
    
    //2018-12-30 增加
	List<TypeItem> selectTypeItemsByTypeId(@Param("IdType") int intTypeId);
}