package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class Macro {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Macro.Id_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private Integer idMacro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Macro.Name_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private String nameMacro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Macro.Value_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private String valueMacro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Macro.Memo_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private String memoMacro;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Macro(Integer idMacro, String nameMacro, String valueMacro, String memoMacro) {
		this.idMacro = idMacro;
		this.nameMacro = nameMacro;
		this.valueMacro = valueMacro;
		this.memoMacro = memoMacro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Macro() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Macro.Id_Macro
	 * @return  the value of Macro.Id_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Integer getIdMacro() {
		return idMacro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Macro.Id_Macro
	 * @param idMacro  the value for Macro.Id_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setIdMacro(Integer idMacro) {
		this.idMacro = idMacro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Macro.Name_Macro
	 * @return  the value of Macro.Name_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public String getNameMacro() {
		return nameMacro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Macro.Name_Macro
	 * @param nameMacro  the value for Macro.Name_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setNameMacro(String nameMacro) {
		this.nameMacro = nameMacro == null ? null : nameMacro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Macro.Value_Macro
	 * @return  the value of Macro.Value_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public String getValueMacro() {
		return valueMacro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Macro.Value_Macro
	 * @param valueMacro  the value for Macro.Value_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setValueMacro(String valueMacro) {
		this.valueMacro = valueMacro == null ? null : valueMacro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Macro.Memo_Macro
	 * @return  the value of Macro.Memo_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public String getMemoMacro() {
		return memoMacro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Macro.Memo_Macro
	 * @param memoMacro  the value for Macro.Memo_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setMemoMacro(String memoMacro) {
		this.memoMacro = memoMacro == null ? null : memoMacro.trim();
	}
}