package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class MacroProjectRelation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MacroProjectRelation.Id_MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private Integer idMacroprojectrelation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MacroProjectRelation.Id_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private Integer idMacro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MacroProjectRelation.Id_Project
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private Integer idProject;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public MacroProjectRelation(Integer idMacroprojectrelation, Integer idMacro, Integer idProject) {
		this.idMacroprojectrelation = idMacroprojectrelation;
		this.idMacro = idMacro;
		this.idProject = idProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public MacroProjectRelation() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MacroProjectRelation.Id_MacroProjectRelation
	 * @return  the value of MacroProjectRelation.Id_MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Integer getIdMacroprojectrelation() {
		return idMacroprojectrelation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MacroProjectRelation.Id_MacroProjectRelation
	 * @param idMacroprojectrelation  the value for MacroProjectRelation.Id_MacroProjectRelation
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setIdMacroprojectrelation(Integer idMacroprojectrelation) {
		this.idMacroprojectrelation = idMacroprojectrelation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MacroProjectRelation.Id_Macro
	 * @return  the value of MacroProjectRelation.Id_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Integer getIdMacro() {
		return idMacro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MacroProjectRelation.Id_Macro
	 * @param idMacro  the value for MacroProjectRelation.Id_Macro
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setIdMacro(Integer idMacro) {
		this.idMacro = idMacro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MacroProjectRelation.Id_Project
	 * @return  the value of MacroProjectRelation.Id_Project
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Integer getIdProject() {
		return idProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MacroProjectRelation.Id_Project
	 * @param idProject  the value for MacroProjectRelation.Id_Project
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}
}