package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class Type {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Type.Id_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private Integer idType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Type.Name_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private String nameType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Type.Memo_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private String memoType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Type.Modifier_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private String modifierType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Type.IsSampleType_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private Integer issampletypeType;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Type(Integer idType, String nameType, String memoType, String modifierType, Integer issampletypeType) {
		this.idType = idType;
		this.nameType = nameType;
		this.memoType = memoType;
		this.modifierType = modifierType;
		this.issampletypeType = issampletypeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Type() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Type.Id_Type
	 * @return  the value of Type.Id_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Integer getIdType() {
		return idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Type.Id_Type
	 * @param idType  the value for Type.Id_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Type.Name_Type
	 * @return  the value of Type.Name_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public String getNameType() {
		return nameType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Type.Name_Type
	 * @param nameType  the value for Type.Name_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setNameType(String nameType) {
		this.nameType = nameType == null ? null : nameType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Type.Memo_Type
	 * @return  the value of Type.Memo_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public String getMemoType() {
		return memoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Type.Memo_Type
	 * @param memoType  the value for Type.Memo_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setMemoType(String memoType) {
		this.memoType = memoType == null ? null : memoType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Type.Modifier_Type
	 * @return  the value of Type.Modifier_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public String getModifierType() {
		return modifierType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Type.Modifier_Type
	 * @param modifierType  the value for Type.Modifier_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setModifierType(String modifierType) {
		this.modifierType = modifierType == null ? null : modifierType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Type.IsSampleType_Type
	 * @return  the value of Type.IsSampleType_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Integer getIssampletypeType() {
		return issampletypeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Type.IsSampleType_Type
	 * @param issampletypeType  the value for Type.IsSampleType_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setIssampletypeType(Integer issampletypeType) {
		this.issampletypeType = issampletypeType;
	}
}