package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class TypeItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeItem.Id_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private Integer idTypeitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeItem.NO_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private Integer noTypeitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeItem.Id_ParentType
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private Integer idParenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeItem.Name_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private String nameTypeitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeItem.DefaultValue_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private String defaultvalueTypeitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeItem.Memo_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private String memoTypeitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeItem.IsSampleType_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private Integer issampletypeTypeitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeItem.Id_SelfType
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private Integer idSelftype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public TypeItem(Integer idTypeitem, Integer noTypeitem, Integer idParenttype, String nameTypeitem, String defaultvalueTypeitem, String memoTypeitem, Integer issampletypeTypeitem, Integer idSelftype) {
        this.idTypeitem = idTypeitem;
        this.noTypeitem = noTypeitem;
        this.idParenttype = idParenttype;
        this.nameTypeitem = nameTypeitem;
        this.defaultvalueTypeitem = defaultvalueTypeitem;
        this.memoTypeitem = memoTypeitem;
        this.issampletypeTypeitem = issampletypeTypeitem;
        this.idSelftype = idSelftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public TypeItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeItem.Id_TypeItem
     *
     * @return the value of TypeItem.Id_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public Integer getIdTypeitem() {
        return idTypeitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeItem.Id_TypeItem
     *
     * @param idTypeitem the value for TypeItem.Id_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setIdTypeitem(Integer idTypeitem) {
        this.idTypeitem = idTypeitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeItem.NO_TypeItem
     *
     * @return the value of TypeItem.NO_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public Integer getNoTypeitem() {
        return noTypeitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeItem.NO_TypeItem
     *
     * @param noTypeitem the value for TypeItem.NO_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setNoTypeitem(Integer noTypeitem) {
        this.noTypeitem = noTypeitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeItem.Id_ParentType
     *
     * @return the value of TypeItem.Id_ParentType
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public Integer getIdParenttype() {
        return idParenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeItem.Id_ParentType
     *
     * @param idParenttype the value for TypeItem.Id_ParentType
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setIdParenttype(Integer idParenttype) {
        this.idParenttype = idParenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeItem.Name_TypeItem
     *
     * @return the value of TypeItem.Name_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public String getNameTypeitem() {
        return nameTypeitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeItem.Name_TypeItem
     *
     * @param nameTypeitem the value for TypeItem.Name_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setNameTypeitem(String nameTypeitem) {
        this.nameTypeitem = nameTypeitem == null ? null : nameTypeitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeItem.DefaultValue_TypeItem
     *
     * @return the value of TypeItem.DefaultValue_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public String getDefaultvalueTypeitem() {
        return defaultvalueTypeitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeItem.DefaultValue_TypeItem
     *
     * @param defaultvalueTypeitem the value for TypeItem.DefaultValue_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setDefaultvalueTypeitem(String defaultvalueTypeitem) {
        this.defaultvalueTypeitem = defaultvalueTypeitem == null ? null : defaultvalueTypeitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeItem.Memo_TypeItem
     *
     * @return the value of TypeItem.Memo_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public String getMemoTypeitem() {
        return memoTypeitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeItem.Memo_TypeItem
     *
     * @param memoTypeitem the value for TypeItem.Memo_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setMemoTypeitem(String memoTypeitem) {
        this.memoTypeitem = memoTypeitem == null ? null : memoTypeitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeItem.IsSampleType_TypeItem
     *
     * @return the value of TypeItem.IsSampleType_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public Integer getIssampletypeTypeitem() {
        return issampletypeTypeitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeItem.IsSampleType_TypeItem
     *
     * @param issampletypeTypeitem the value for TypeItem.IsSampleType_TypeItem
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setIssampletypeTypeitem(Integer issampletypeTypeitem) {
        this.issampletypeTypeitem = issampletypeTypeitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeItem.Id_SelfType
     *
     * @return the value of TypeItem.Id_SelfType
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public Integer getIdSelftype() {
        return idSelftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeItem.Id_SelfType
     *
     * @param idSelftype the value for TypeItem.Id_SelfType
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setIdSelftype(Integer idSelftype) {
        this.idSelftype = idSelftype;
    }
}