package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class TypeProjectRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeProjectRelation.Id_TypeProjectRelation
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private Integer idTypeprojectrelation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeProjectRelation.Id_Type
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private Integer idType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TypeProjectRelation.Id_Project
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    private Integer idProject;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TypeProjectRelation
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public TypeProjectRelation(Integer idTypeprojectrelation, Integer idType, Integer idProject) {
        this.idTypeprojectrelation = idTypeprojectrelation;
        this.idType = idType;
        this.idProject = idProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TypeProjectRelation
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public TypeProjectRelation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeProjectRelation.Id_TypeProjectRelation
     *
     * @return the value of TypeProjectRelation.Id_TypeProjectRelation
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public Integer getIdTypeprojectrelation() {
        return idTypeprojectrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeProjectRelation.Id_TypeProjectRelation
     *
     * @param idTypeprojectrelation the value for TypeProjectRelation.Id_TypeProjectRelation
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setIdTypeprojectrelation(Integer idTypeprojectrelation) {
        this.idTypeprojectrelation = idTypeprojectrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeProjectRelation.Id_Type
     *
     * @return the value of TypeProjectRelation.Id_Type
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public Integer getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeProjectRelation.Id_Type
     *
     * @param idType the value for TypeProjectRelation.Id_Type
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setIdType(Integer idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TypeProjectRelation.Id_Project
     *
     * @return the value of TypeProjectRelation.Id_Project
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public Integer getIdProject() {
        return idProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TypeProjectRelation.Id_Project
     *
     * @param idProject the value for TypeProjectRelation.Id_Project
     *
     * @mbg.generated Sun Dec 30 11:32:24 CST 2018
     */
    public void setIdProject(Integer idProject) {
        this.idProject = idProject;
    }
}