package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class VarItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.Id_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private Integer idVaritem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.Id_Var
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private Integer idVar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.Name_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private String nameVaritem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.Value_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private String valueVaritem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.Memo_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private String memoVaritem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.Id_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private Integer idType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.IsSampleType_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	private Integer issampletypeVaritem;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public VarItem(Integer idVaritem, Integer idVar, String nameVaritem, String valueVaritem, String memoVaritem,
			Integer idType, Integer issampletypeVaritem) {
		this.idVaritem = idVaritem;
		this.idVar = idVar;
		this.nameVaritem = nameVaritem;
		this.valueVaritem = valueVaritem;
		this.memoVaritem = memoVaritem;
		this.idType = idType;
		this.issampletypeVaritem = issampletypeVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public VarItem() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.Id_VarItem
	 * @return  the value of VarItem.Id_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Integer getIdVaritem() {
		return idVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.Id_VarItem
	 * @param idVaritem  the value for VarItem.Id_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setIdVaritem(Integer idVaritem) {
		this.idVaritem = idVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.Id_Var
	 * @return  the value of VarItem.Id_Var
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Integer getIdVar() {
		return idVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.Id_Var
	 * @param idVar  the value for VarItem.Id_Var
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setIdVar(Integer idVar) {
		this.idVar = idVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.Name_VarItem
	 * @return  the value of VarItem.Name_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public String getNameVaritem() {
		return nameVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.Name_VarItem
	 * @param nameVaritem  the value for VarItem.Name_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setNameVaritem(String nameVaritem) {
		this.nameVaritem = nameVaritem == null ? null : nameVaritem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.Value_VarItem
	 * @return  the value of VarItem.Value_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public String getValueVaritem() {
		return valueVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.Value_VarItem
	 * @param valueVaritem  the value for VarItem.Value_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setValueVaritem(String valueVaritem) {
		this.valueVaritem = valueVaritem == null ? null : valueVaritem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.Memo_VarItem
	 * @return  the value of VarItem.Memo_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public String getMemoVaritem() {
		return memoVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.Memo_VarItem
	 * @param memoVaritem  the value for VarItem.Memo_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setMemoVaritem(String memoVaritem) {
		this.memoVaritem = memoVaritem == null ? null : memoVaritem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.Id_Type
	 * @return  the value of VarItem.Id_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Integer getIdType() {
		return idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.Id_Type
	 * @param idType  the value for VarItem.Id_Type
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.IsSampleType_VarItem
	 * @return  the value of VarItem.IsSampleType_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public Integer getIssampletypeVaritem() {
		return issampletypeVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.IsSampleType_VarItem
	 * @param issampletypeVaritem  the value for VarItem.IsSampleType_VarItem
	 * @mbg.generated  Sun Dec 30 11:32:24 CST 2018
	 */
	public void setIssampletypeVaritem(Integer issampletypeVaritem) {
		this.issampletypeVaritem = issampletypeVaritem;
	}
}